// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jsnkhzdtbgxzweuoydyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzbmtoemR0Ymd4endldW95ZHl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MTM0NjMsImV4cCI6MjA1ODI4OTQ2M30.QOkQhhMvv3RemxcpKZeGs94c1zw51rI51OFc3KpZIpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);